[split-monitor-workspaces]
description = "Split monitor workspaces"
version = "1.1.0"
author = "Duckonaut"

[split-monitor-workspaces.build]
output = "build/libsplit-monitor-workspaces.so"
steps = [
    "meson setup build --wipe",
    "meson compile -C build",
]
